/**
 * AUTO-GENERATED by scripts/generate-environment.mjs — do not edit by hand.
 */
export interface AppEnvironment {
  /** Absolute origin of the API, e.g. https://api.example.com */
  apiBaseUrl: string;
  /** Extra origins allowed by the CSP connect-src directive. */
  cspConnectSrc: string[];
}

export const environment: AppEnvironment = {
  apiBaseUrl: "",
  cspConnectSrc: [],
};
